import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '../Components/Navbar';
import Chart from "../Components/Chart" 
import Desc from "../Components/Description" 
import Users from "../Components/Users" 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <Nav/>
        {children}
        <Chart/>
        <Desc/>
        <Users/>
        </body>
    </html>
  );
}
