import type { Metadata } from "next";
import "./globals.css";
import Nav from '../MyComponents/Navbar';
import Chart from "../MyComponents/Chart" 
import Desc from "../MyComponents/Description" 
import Users from "../MyComponents/Users" 
import Provider from '../MyComponents/lib/Provider';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <Provider>
      <Nav/>
        {children}
        <Chart/>
        <Desc/>
        <Users/>
        </Provider>
        </body>
    </html>
  );
}
